name: "Build Test"

on:
  workflow_dispatch:
    inputs:
      sign-build:
        description: 'Sign the build (requires secrets to be set)'
        required: false
        type: boolean
        default: false
  pull_request:
    branches: [main]

jobs:
  build-test:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
            args: "--bundles deb"
            target: "x86_64-unknown-linux-gnu"

    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      sign-binaries: ${{ github.event.inputs.sign-build == 'true' }}
      asset-prefix: "poly-test"
      upload-artifacts: true
      is-debug-build: ${{ contains(matrix.args, '--debug') }}
      run-tests: true
    secrets: inherit
